name: Honey Heist CD

on:
  workflow_dispatch:
    branches: [release]

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: fregante/setup-git-user@v1

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Release
        run: |
          npx semantic-release
